-- ALX_BOOK_STORE DATABASE SCHEMA

CREATE DATABASE IF NOT EXISTS alx_book_store;
USE ALX_BOOK_STORE;

-- DROP TABLES IF THEY ALREADY EXIST (IN FK-SAFE ORDER)
DROP TABLE IF EXISTS ORDER_DETAILS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS CUSTOMERS;

-- AUTHORS: STORES INFORMATION ABOUT AUTHORS
CREATE TABLE AUTHORS (
  AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(215) NOT NULL
) ENGINE=INNODB;

-- BOOKS: STORES INFORMATION ABOUT BOOKS
CREATE TABLE BOOKS (
  BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  PRICE DOUBLE NOT NULL,
  PUBLICATION_DATE DATE,
  CONSTRAINT FK_BOOKS_AUTHOR
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- CUSTOMERS: STORES INFORMATION ABOUT CUSTOMERS
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215),
  ADDRESS TEXT
) ENGINE=INNODB;

-- ORDERS: STORES ORDERS PLACED BY CUSTOMERS
CREATE TABLE ORDERS (
  ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  ORDER_DATE DATE NOT NULL,
  CONSTRAINT FK_ORDERS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- ORDER_DETAILS: STORES THE BOOKS INCLUDED IN EACH ORDER
CREATE TABLE ORDER_DETAILS (
  ORDERDETAILID INT AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  QUANTITY DOUBLE NOT NULL,
  CONSTRAINT FK_OD_ORDER
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_OD_BOOK
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- OPTIONAL: HELPFUL INDEXES FOR FASTER JOINS/LOOKUPS
CREATE INDEX IDX_BOOKS_AUTHOR_ID ON BOOKS (AUTHOR_ID);
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS (CUSTOMER_ID);
CREATE INDEX IDX_OD_ORDER_ID ON ORDER_DETAILS (ORDER_ID);
CREATE INDEX IDX_OD_BOOK_ID ON ORDER_DETAILS (BOOK_ID);
