-- ALX_BOOK_STORE DATABASE SCHEMA

CREATE DATABASE IF NOT EXISTS alx_book_store;
USE ALX_BOOK_STORE;

-- DROP TABLES IF THEY ALREADY EXIST (IN FK-SAFE ORDER)
DROP TABLE IF EXISTS ORDER_DETAILS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS CUSTOMERS;

-- AUTHORS: STORES INFORMATION ABOUT AUTHORS
CREATE TABLE Authors (
  author_id INT AUTO_INCREMENT PRIMARY KEY,
  author_name VARCHAR(215) NOT NULL
) ENGINE=INNODB;

-- BOOKS: STORES INFORMATION ABOUT BOOKS
CREATE TABLE Books (
  book_id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(130) NOT NULL,
  author_id INT NOT NULL,
  price DOUBLE NOT NULL,
  publication_date DATE,
  CONSTRAINT FK_BOOKS_AUTHOR
    FOREIGN KEY (author_id) REFERENCES Authors(author_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- CUSTOMERS: STORES INFORMATION ABOUT CUSTOMERS
CREATE TABLE Customers (
  customer_id INT AUTO_INCREMENT PRIMARY KEY,
  customer_name VARCHAR(215) NOT NULL,
  email VARCHAR(215),
  address TEXT
) ENGINE=INNODB;

-- ORDERS: STORES ORDERS PLACED BY CUSTOMERS
CREATE TABLE Orders (
  order_id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_date DATE NOT NULL,
  CONSTRAINT FK_ORDERS_CUSTOMER
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- ORDER_DETAILS: STORES THE BOOKS INCLUDED IN EACH ORDER
CREATE TABLE Order_Details (
  orderdetailid INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  book_id INT NOT NULL,
  quantity DOUBLE NOT NULL,
  CONSTRAINT FK_OD_ORDER
    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_OD_BOOK
    FOREIGN KEY (book_id) REFERENCES Books(book_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=INNODB;

-- OPTIONAL: HELPFUL INDEXES FOR FASTER JOINS/LOOKUPS
CREATE INDEX IDX_BOOKS_AUTHOR_ID ON Books (author_id);
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON Orders (customer_id);
CREATE INDEX IDX_OD_ORDER_ID ON Order_Details (order_id);
CREATE INDEX IDX_OD_BOOK_ID ON Order_Details (book_id);
